### ISSUE TITLE
Reflect.parse crash with "ImportClause : ImportedDefaultBinding , NamedImports"

### ISSUE THREAD

**Issue by ziyunfei** [anba/es6draft#10]
```
js> Reflect.parse(`import a,{b} from ""`)
com.github.anba.es6draft.runtime.objects.reflect.ReflectParser$NotImplementedExpception: class com.github.anba.es6draft.ast.ImportClause
	at com.github.anba.es6draft.runtime.objects.reflect.ReflectParser.visit(ReflectParser.java:1552)
	at com.github.anba.es6draft.runtime.objects.reflect.ReflectParser.visit(ReflectParser.java:42)
	at com.github.anba.es6draft.ast.ImportClause.accept(ImportClause.java:42)
	at com.github.anba.es6draft.runtime.objects.reflect.ReflectParser.visit(ReflectParser.java:1523)
	at com.github.anba.es6draft.runtime.objects.reflect.ReflectParser.visit(ReflectParser.java:42)
	at com.github.anba.es6draft.ast.ImportDeclaration.accept(ImportDeclaration.java:51)
	at com.github.anba.es6draft.runtime.objects.reflect.ReflectParser.createList(ReflectParser.java:416)
	at com.github.anba.es6draft.runtime.objects.reflect.ReflectParser.visit(ReflectParser.java:1718)
	at com.github.anba.es6draft.runtime.objects.reflect.ReflectParser.visit(ReflectParser.java:42)
	at com.github.anba.es6draft.ast.Module.accept(Module.java:61)
	at com.github.anba.es6draft.runtime.objects.reflect.ReflectParser.parse(ReflectParser.java:275)
	at com.github.anba.es6draft.runtime.objects.reflect.ReflectParser.parse(ReflectParser.java:239)
	at com.github.anba.es6draft.runtime.objects.reflect.Reflect$ParseProperty.parse(Reflect.java:509)
	at #typein_1.~script(typein:1)
	at com.github.anba.es6draft.runtime.internal.RuntimeInfo$CompiledScriptBody.evaluate(RuntimeInfo.java:289)
	at com.github.anba.es6draft.compiler.CompiledScript.evaluate(CompiledScript.java:28)
	at com.github.anba.es6draft.Scripts.ScriptEvaluation(Scripts.java:44)
	at com.github.anba.es6draft.repl.Repl.eval(Repl.java:785)
	at com.github.anba.es6draft.repl.Repl.access$300(Repl.java:97)
	at com.github.anba.es6draft.repl.Repl$InteractiveTaskSource$EvalPrintTask.execute(Repl.java:914)
	at ...(Frames omitted:4)

**Comment by anba** [comment]
That exception was (more or less) a reminder for me to handle this case when SpiderMonkey's `Reflect.parse` supports that syntax. But actually there's no real reason why I shouldn't just support this syntax now. So thanks for reporting! :smile:
