### ISSUE TITLE
Misbehaving RegExp-likes can crash the VM

### ISSUE THREAD

**Issue by jugglinmike** [anba/es6draft#11]
If a "RegExp-like" object sets its own `lastIndex` property to an out-of-bounds
value during a "split" operation, es6draft will crash.

Example:

```js
var obj = {
  constructor: function() {}
};
var fakeRe = {
  exec: function() {
    fakeRe.lastIndex = 999;
    return [];
  }
};
obj.constructor[Symbol.species] = function() {
  return fakeRe;
};

RegExp.prototype[Symbol.split].call(obj, 'a');
```

Produces the following error:

    java.lang.StringIndexOutOfBoundsException: String index out of range: -998
      at java.lang.String.substring(String.java:1955)
      at com.github.anba.es6draft.runtime.objects.text.RegExpPrototype$Properties.split(RegExpPrototype.java:672)
      at com.github.anba.es6draft.runtime.types.builtins.NativeFunction.call(NativeFunction.java:97)
      at com.github.anba.es6draft.runtime.types.builtins.BuiltinFunction.tailCall(BuiltinFunction.java:206)
      at com.github.anba.es6draft.runtime.internal.TailCallInvocation$CallTailCallInvocation.apply(TailCallInvocation.java:66)
      at com.github.anba.es6draft.runtime.internal.TailCallInvocation.tailCallTrampoline(TailCallInvocation.java:179)
      at #typein_1.~script_code(/test262/tmp2.js:14)
      at #typein_1.!script(/test262/tmp2.js:1)
      at com.github.anba.es6draft.runtime.internal.RuntimeInfo$CompiledScriptBody.evaluate(RuntimeInfo.java:233)
      at com.github.anba.es6draft.compiler.CompiledScript.evaluate(CompiledScript.java:29)
      at com.github.anba.es6draft.repl.Repl.eval(Repl.java:801)
      at com.github.anba.es6draft.repl.Repl.access$300(Repl.java:89)
      at com.github.anba.es6draft.repl.Repl$ScriptEvaluationTask.execute(Repl.java:1146)
      at com.github.anba.es6draft.runtime.World.executeTasks(World.java:223)
      at com.github.anba.es6draft.runtime.World.runEventLoop(World.java:200)
      at com.github.anba.es6draft.repl.Repl.loop(Repl.java:827)
      at com.github.anba.es6draft.repl.Repl.main(Repl.java:100)

Here's [the relevant source code](https://github.com/anba/es6draft/blob/8d9300fccfb8f641f3c108a6e8c8804fa7e4de9d/src/main/java/com/github/anba/es6draft/runtime/objects/text/RegExpPrototype.java#L671-L672):

```java
/* step 25 */
String t = s.substring(p, size);
```

This seems like it may be an omission in the spec itself, since an explicit
RangeError might be appropriate here. I've opened a bug on the spec bug tracker
to discuss that possibility: https://bugs.ecmascript.org/show_bug.cgi?id=4434

As it stands, though, the most logical behavior may be to silently skip
appending the final string value.

**Comment by anba** [comment]
Nice find! Didn't spot that issue when spec reviewing and implementing this part!

**Comment by anba** [comment]
> This seems like it may be an omission in the spec itself, since an explicit
> RangeError might be appropriate here. I've opened a bug on the spec bug tracker
> to discuss that possibility: https://bugs.ecmascript.org/show_bug.cgi?id=4434
> 
> As it stands, though, the most logical behavior may be to silently skip
> appending the final string value.

I went with the latter option, so out-of-bounds access is treated like in `RegExp.prototype[@@split]`.

Previous string indexing issues for `RegExp.prototype[@@split]`:
https://bugs.ecmascript.org/show_bug.cgi?id=2780
https://bugs.ecmascript.org/show_bug.cgi?id=2849
