### ISSUE TITLE
crash in RegExp.prototype[ @@replace ]

### ISSUE THREAD

**Issue by ziyunfei** [anba/es6draft#6]
```
js> (new class extends RegExp {
  exec(){
    return {index: 0};
  }
})[Symbol.replace]("a", "b")
java.lang.NullPointerException
	at com.github.anba.es6draft.runtime.objects.text.RegExpPrototype$Properties.replace(RegExpPrototype.java:470)
	at #typein_1.~script(typein:3)
	at com.github.anba.es6draft.runtime.internal.RuntimeInfo$CompiledScriptBody.evaluate(RuntimeInfo.java:310)
	at com.github.anba.es6draft.compiler.CompiledScript.evaluate(CompiledScript.java:28)
	at com.github.anba.es6draft.Scripts.ScriptEvaluation(Scripts.java:50)
	at com.github.anba.es6draft.repl.Repl.eval(Repl.java:782)
	at com.github.anba.es6draft.repl.Repl.access$300(Repl.java:97)
	at com.github.anba.es6draft.repl.Repl$InteractiveTaskSource$EvalPrintTask.execute(Repl.java:911)
	at com.github.anba.es6draft.runtime.World.executeTasks(World.java:221)
	at com.github.anba.es6draft.runtime.World.runEventLoop(World.java:198)
	at com.github.anba.es6draft.repl.Repl.loop(Repl.java:808)
	at com.github.anba.es6draft.repl.Repl.main(Repl.java:108)
```

**Comment by anba** [comment]
Confirmed. Thanks for the report!

Similar issues are present for these examples:
```javascript
// NPE at com.github.anba.es6draft.runtime.objects.text.RegExpPrototype$Properties.replace(RegExpPrototype.java:444)
(new class extends RegExp {
  get global() {
    return true;
  }
  exec(){
    return {index: 0};
  }
})[Symbol.replace]("a", "b")

// NPE at com.github.anba.es6draft.runtime.objects.text.RegExpPrototype$Properties.match(RegExpPrototype.java:370)
(new class extends RegExp {
  get global() {
    return true;
  }
  exec(){
    return {index: 0};
  }
})[Symbol.match]("a")
```
